FROM almalinux:9
ENV course="Devops with AWS" \
    trainer="sivakumar" \
    duration="120HRS"
#here user1 is key ..someuser is default value
ARG USERNAME=soumya
RUN echo "Hello User: ${USERNAME}" > /tmp/devops.txt
CMD ["sleep", "200"]

    